# Generated by Django 4.2.13 on 2024-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.CharField(max_length=3000),
        ),
    ]
